#ifndef __STUB__H__
#define __STUB__H__

#define MULTIBOOT2_MAGIC 0xE85250D6
#define MULTIBOOT2_ARCH_I386 0
#define MULTIBOOT2_HEADER_LENGTH 0
#define MULTIBOOT2_CHECKSUM (-(MULTIBOOT2_MAGIC + MULTIBOOT2_ARCH_I386 + MULTIBOOT2_HEADER_LENGTH))


#endif